version: '3'

services:
  postgresql:
      image: postgres:latest

      ports:
        - 5432:5432

      volumes:
        - /opt/postgres/data:/var/lib/postgresql/data

      environment:
        POSTGRES_USER: metro
        POSTGRES_PASSWORD: metro
        POSTGRES_DBNAME: metro

